# Generated by Django 5.2.2 on 2025-06-16 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodredistribution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIPerformanceMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('total_matches_generated', models.IntegerField(default=0)),
                ('successful_matches', models.IntegerField(default=0)),
                ('average_match_score', models.FloatField(default=0.0)),
                ('average_feedback_rating', models.FloatField(default=0.0)),
            ],
            options={
                'unique_together': {('date',)},
            },
        ),
    ]
