# Generated by Django 5.2.2 on 2025-06-19 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandDataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('donation_volume', models.PositiveIntegerField()),
                ('request_volume', models.PositiveIntegerField()),
                ('special_event', models.CharField(blank=True, max_length=255, null=True)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
